"""Archive API v2 — REST endpoints for storing/retrieving Claude Code transcripts.

New on branch `new-features`:
- /sessions/search-semantic     — semantic search via Qdrant
- /sessions/{id}/summarize      — generate LLM summary on demand
- /sessions/{id}/context        — load context for continuation (full|compressed|rag)
- /sessions/{id}/transcript     — fetch transcript (from R2 if r2_key set)
- /openapi.json                 — auto-generated by FastAPI (for ChatGPT Custom GPT Actions)

Auth: all endpoints except /health require `Authorization: Bearer <ARCHIVE_AUTH_TOKEN>`.
"""
import os
import psycopg2
from psycopg2.extras import Json, RealDictCursor
from fastapi import FastAPI, Header, HTTPException, Query
from pydantic import BaseModel
from typing import Optional, Literal

# Optional features — graceful if env not set
try:
    from . import summarizer, embeddings, qdrant_helper, r2_storage
except ImportError:
    import summarizer, embeddings, qdrant_helper, r2_storage  # type: ignore

DB_URL = os.environ["DB_URL"]
AUTH = os.environ["ARCHIVE_AUTH_TOKEN"]
USE_R2 = bool(os.environ.get("R2_ENDPOINT_URL"))
USE_SEMANTIC = bool(os.environ.get("OPENAI_API_KEY"))

app = FastAPI(
    title="Chat Archive API",
    description="Archive of past Claude/ChatGPT conversations. "
                "Supports keyword search, semantic search, and context loading "
                "for continuing past conversations.",
    version="2.0.0",
    servers=[{"url": "https://claude.hangocthanh.io.vn/archive"}],
)


def check(token):
    if not token or token != f"Bearer {AUTH}":
        raise HTTPException(401, "Unauthorized")


def conn():
    return psycopg2.connect(DB_URL, cursor_factory=RealDictCursor)


# ============================================================
# chat_sessions — create/list/get
# ============================================================

class Session(BaseModel):
    user_id: str
    project_tag: Optional[str] = None
    started_at: str
    ended_at: Optional[str] = None
    message_count: int
    transcript: list
    summary: Optional[str] = None
    workspace_path: Optional[str] = None
    metadata: dict = {}


@app.post("/sessions", summary="Create a new archived session")
def create(s: Session, authorization: str = Header(None)):
    """Create a session. If R2 is configured, transcript is offloaded
    to object storage and only metadata + r2_key kept in Postgres."""
    check(authorization)

    r2_key, r2_size = None, None
    transcript_to_store = s.transcript

    if USE_R2:
        try:
            r2_key, r2_size = r2_storage.upload_transcript(s.user_id, s.transcript)
            transcript_to_store = []  # don't duplicate in Postgres
        except Exception as e:
            # Fallback: keep in DB if R2 fails
            print(f"R2 upload failed, falling back to DB: {e}")

    with conn() as c, c.cursor() as cur:
        cur.execute(
            """
            INSERT INTO chat_sessions
            (user_id, project_tag, started_at, ended_at, message_count,
             transcript, summary, workspace_path, metadata, r2_key, r2_size_bytes)
            VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
            RETURNING id
            """,
            (s.user_id, s.project_tag, s.started_at, s.ended_at,
             s.message_count, Json(transcript_to_store), s.summary,
             s.workspace_path, Json(s.metadata), r2_key, r2_size),
        )
        sid = str(cur.fetchone()["id"])

    return {"id": sid, "r2_key": r2_key}


@app.get("/sessions", summary="List/search sessions by metadata")
def list_sessions(
    user_id: str,
    project_tag: Optional[str] = None,
    date_from: Optional[str] = None,
    date_to: Optional[str] = None,
    q: Optional[str] = Query(None, description="Keyword search in summary (ILIKE)"),
    limit: int = 100,
    authorization: str = Header(None),
):
    check(authorization)
    sql = (
        "SELECT id, started_at, project_tag, message_count, "
        "COALESCE(llm_summary, summary) AS summary "
        "FROM chat_sessions WHERE user_id=%s"
    )
    args = [user_id]
    if project_tag:
        sql += " AND project_tag=%s"
        args.append(project_tag)
    if date_from:
        sql += " AND started_at >= %s"
        args.append(date_from)
    if date_to:
        sql += " AND started_at <= %s"
        args.append(date_to)
    if q:
        sql += " AND (COALESCE(llm_summary, summary) ILIKE %s)"
        args.append(f"%{q}%")
    sql += " ORDER BY started_at DESC LIMIT %s"
    args.append(limit)
    with conn() as c, c.cursor() as cur:
        cur.execute(sql, args)
        return [dict(r) for r in cur.fetchall()]


@app.get("/sessions/search-semantic", summary="Semantic search via Qdrant")
def search_semantic(
    q: str,
    user_id: str,
    limit: int = 10,
    authorization: str = Header(None),
):
    """Embed query, find top-K similar sessions by summary."""
    check(authorization)
    if not USE_SEMANTIC:
        raise HTTPException(503, "Semantic search not configured (OPENAI_API_KEY missing)")

    qvec = embeddings.embed(q)
    hits = qdrant_helper.search(qvec, limit=limit, user_id=user_id)
    if not hits:
        return []

    # Hydrate from Postgres
    ids = [h["id"] for h in hits]
    score_map = {h["id"]: h["score"] for h in hits}
    with conn() as c, c.cursor() as cur:
        cur.execute(
            "SELECT id, started_at, project_tag, message_count,